version: '3.8'

services:
  api-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://localhostpostgres@postgres:5432/?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api-server

volumes:
  postgres_data:
